sudo: true
language: python
python:
  - "3.6"
  - "nightly"

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

install:
  - pip install -r requirements/dev.txt

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - sudo chmod +x $PWD/geckodriver/geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - nosetests --with-cov --cov-config .coveragerc --cov ci_demo tests/

after_success:
  - codecov
jobs:
  include:
    - stage: Deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: qP3K+nyr3MjsfMPEW6iSdX5gRBvoMHMk1VpWBSjktlYHawsxFbrGsStelgvpLRH9w+7TXuiOwyFihY9e+PU086Sb7BiWpm03ST/5DdtRIhyKfT6YTIsPEsw9Kjr/Jpj+eP5bi3oBeag1Vg8IAc54mizTHSh4Fjqv8l3qVEO+jC5IuZAyV3xZj2i7bCQm9LFiSWnrOrgEVywVdm4iYr0+TZBGmwsCfjY/q2umPU38WVJNiYdVv6HmwmNZB1mrNHQbzXasyJEHX7gZzRHPESFDNFqUHndQVA7GUEGlVt9DMFu+cCOKa2G7mb4IWOZpI8bdd4diD9e+N5u52sTAbVpQg/USQG3LwFTDXghY8vXXH1edjmbP2vVkQRaM8WZU8u9rbUCJ68L7+F2rhcNxEyCYaGf3bl75dGcZ20eWmAWQ2+yOTjHDPQbhcKfN2QSUWwtNRnWu8DTqfTg2/PhWSz34P4SJOUaDK1N/c98CV1UVUZpK41PLgEDci1gyti7AEnkXVEnoqSQ9S4V2FhLs67tRIKEJZ2qH3NA5ri2IRyu2FikYwArQouHlIslr86ObIKG3eq4mBVdK7LYVFrskq86xPxpjYKzAEwmqlMdF+X9T/kB5hbgyk2Xwm5RAyMp114MEUcRrxpdMGj+ps7c+16pe9SYc3L/KV4zfDIku8ux3osk=
          app: ci-workshop-rom
        on:
          repo: rohubert/ci_workshop
